include {
    sniffles2;
    filterCalls;
    sortVCF;
    makeStatsJson;
} from "../modules/local/wf-human-sv.nf"
include {
    filterBenchmarkVcf;
    intersectBedWithTruthset;
    truvari;
} from "../modules/local/wf-human-sv-eval.nf"
include {
    annotate_vcf as annotate_sv_vcf;
    haploblocks as haploblocks_sv
} from '../modules/local/common.nf'
include {
    optionalBoundaryPath
} from '../lib/optional_inputs.nf'

workflow bam {
    take:
        bam_channel
        reference
        target
        mosdepth_stats
        optional_file
        genome_build
        chromosome_codes
        workflow_params
    main:
        called = variantCall(bam_channel, reference, target, mosdepth_stats, optional_file, genome_build, chromosome_codes)

        // benchmark
        if (params.sv_benchmark) {
            maybe_benchmark_result = runBenchmark(called.vcf, reference, target)
        }
        else {
            maybe_benchmark_result = Channel.empty()
        }

        if (!params.annotation) {
            final_vcf = called.vcf.join(called.vcf_index)

            sv_metrics = makeStatsJson(called.vcf)
            sv_stats_json = sv_metrics.json
        }
        else {
            // append '*' to indicate that annotation should be performed on all chr at once
            vcf_for_annotation = called.vcf.join(called.vcf_index).map{ it << '*' }
            // annotate with SnpEff
            final_vcf = annotate_sv_vcf(vcf_for_annotation, genome_build, "sv").annot_vcf
            sv_metrics = makeStatsJson(final_vcf.map{meta, vcf, tbi -> [meta, vcf]})
            sv_stats_json = sv_metrics.json
        }

        // Prepare stuff to emit
        output = Channel.empty().concat(
            final_vcf.map{meta, vcf, tbi -> [vcf, tbi]},
            maybe_benchmark_result
        )
    
    emit:
        output = output
        sv_stats_json = sv_stats_json
        sniffles_vcf = called.vcf
        for_phasing = final_vcf
}


workflow runBenchmark {
    take:
        vcf
        reference
        target
    main:
        // Transitional Nextflow boundary: controller state should model absent
        // truthsets explicitly; this workflow still maps absence to process-local
        // boundary paths so the bundled SV benchmark resources are selected.

        // reconcile workflow target BED and benchmark truthset BED
        //   recall if user does not input a BED, one covering all genomic
        //   intervals in the ref is generated by getAllChromosomesBed
        if (params.sv_benchmark_bed) {
            truthset_bed = Channel.fromPath(params.sv_benchmark_bed, checkIfExists: true)
        }
        else {
            truthset_bed = optionalBoundaryPath("bed")
        }
        intersected = intersectBedWithTruthset(target, truthset_bed)

        // load user-provided benchmark data
        if (params.sv_benchmark_vcf) {
            // truvari assumes index is [vcf].tbi
            truthset_vcf = Channel.fromPath(params.sv_benchmark_vcf, checkIfExists: true)
            truthset_tbi = Channel.fromPath(params.sv_benchmark_vcf + '.tbi', checkIfExists: true)
        }
        else {
            // Process-local boundary paths trigger bundled benchmark data.
            truthset_vcf = Channel.of(optionalBoundaryPath("vcf.gz"))
            truthset_tbi = Channel.of(optionalBoundaryPath("vcf.gz.tbi"))
        }

        // run benchmark
        filtered = filterBenchmarkVcf(vcf)
        truvari(
            reference,
            filtered,
            truthset_vcf.concat(truthset_tbi).toList(),
            intersected.intersected_bed)
    emit:
        json = truvari.out.truvari_json
}


workflow variantCall {
    take:
        bam_channel
        reference
        target_bed
        mosdepth_stats
        optional_file
        genome_build
        chromosome_codes
    main:

        // tandom_repeat bed
        if(params.tr_bed) {
            tr_bed = Channel.fromPath(params.tr_bed, checkIfExists: true)
        } else {
            tr_bed = optional_file
        }

        if (!genome_build) {
            genome_build = Channel.of(null)
        }

        sniffles2(bam_channel, tr_bed, reference, genome_build)
        filterCalls(sniffles2.out.vcf, mosdepth_stats, target_bed, chromosome_codes)
        sortVCF(filterCalls.out.vcf)

    emit:
        vcf = sortVCF.out.vcf_gz
        vcf_index = sortVCF.out.vcf_tbi
}
